model:
  yaml: "./config/yolov11x-pose-headbar.yaml"
  pretrained: "./pretrained/yolo11x-pose.pt"

data: "./config/headbar.yaml"

project: "runs"
name: "headbar2stage"
cuda_visible_devices: "5"
imgsz: 1920

stages:
  - name: "stage1"
    enabled: False
    epochs: 300
    batch: 8
    workers: 12
    exist_ok: true
    seed: 42
    single_cls: False
    freeze: 10
    optimizer: "AdamW"
    cos_lr: true
    lr0: 0.005
    lrf: 0.01
    cache: "ram"
    patience: 500
    warmup_epochs: 5
    box: 15
    pose: 10
    flipud: 0.5
    fliplr: 0
    shear: 0
    degrees: 90
    mixup: 0.3
    compile: true

  - name: "stage2"
    enabled: true
    epochs: 200
    batch: 4
    workers: 6
    exist_ok: true
    seed: 42
    single_cls: False
    freeze: 0
    optimizer: "AdamW"
    lr0: 0.0001
    lrf: 0.01
    cache: "ram"
    patience: 1000
    box: 10
    pose: 15
    flipud: 0.5
    fliplr: 0
    shear: 0
    degrees: 90
    mixup: 0.3
    compile: true
