model:
  # yaml: config/yolov11m-pose-add-p2-layer.yaml 训练实际使用的配置文件，box only
  yaml: config/add-p2-layer/yolov11-pose.yaml
  pretrained: pretrained/yolo11m-pose.pt
data: dataset/ballmany.yaml

project: "runs"
name: "ballmany"
cuda_visible_devices: "7"
imgsz: 1920

stages:
  - name: "fast"
    enabled: true
    epochs: 20
    batch: 8
    workers: 12
    exist_ok: true
    seed: 42
    single_cls: False
    freeze: 10
    optimizer: "AdamW"
    cos_lr: False
    lr0: 0.005
    lrf: 0.01
    cache: "ram"
    patience: 500
    warmup_epochs: 5
    box: 15
    pose: 10
    flipud: 0.5
    fliplr: 0
    shear: 0
    degrees: 90
    mixup: 0.1
    compile: true

  - name: "fine"
    enabled: true
    epochs: 400
    batch: 3
    workers: 3
    exist_ok: true
    seed: 42
    single_cls: False
    freeze: 0
    optimizer: "AdamW"
    lr0: 0.0001
    # lr1: 0.0001
    # lr2: 0.0001
    cos_lr: true
    lrf: 0.001
    cache: "ram"
    patience: 1000
    box: 10
    pose: 15
    flipud: 0.5
    fliplr: 0
    shear: 0
    degrees: 90
    mixup: 0.1
    compile: true
